### ISSUE TITLE
[RFC] [3.0] Context Aware RBAC

### ISSUE THREAD

**Issue by arekkas** [ZF-Commons/zfc-rbac#241]
## The problem

RBAC is a great system to provide authorization utilities to a software. When dealing with multiple blended systems (shared multi tenancy) RBAC fails to comply. Let's take an example:

1. UserA is an editor on BlogA
* UserA want's to create a new post on blogA -> success
* UserA want's to create a new blog post blogB -> failure
* UserB grants UserA the editor role on blogB
* UserA want's to create a new blog post blogB -> success

This is  currently impossible to do, because all we can do is:

```php
$this->isGranted('post.create');
```

Sure, there are assertions, but do they any good?

```php
public function assert(AuthroizationService $service, $context = NULL)
{
    // We can check for permissions or ownership here, but there is no way to say if UserA has an editor role on blogB
}
```

### pRBAC

https://github.com/dimagi/django-prbac/blob/master/docs/tutorial.rst#id1
https://github.com/dimagi/django-prbac/blob/master/django_prbac/models.py

I have not fully understood that implementation yet, because they do not use classic terms like role and permission but rather role, grant and group. For example, this is how you achieve a simple RBAC:

```
kenn = Role.objects.create(name='kenn')
may_view_reports = Role.create(name='may_view_reports', friendly_name='May view reports')
Grant.objects.create(from_role=kenn , to_role=may_view_reports)
kenn.has_privilege(may_view_reports)
```

Which doesn't make a lot of sence to me at first glance. PRBAC looks like this:

```
kenn = Role.objects.create(name='kenn')
may_view_reports = Role.create(name='may_view_reports', friendly_name='May view reports')
Grant.objects.create(from_role=kenn , to_role=may_view_reports, assignment={'report_name': 'active_users'})
kenn.has_privilege(may_view_report.instantiate({'report_name': 'active_users'}) // true
kenn.has_privilege(may_view_report.instantiate({'report_name': 'something_else'}) // false
```

### Context-aware (or parametrized) Permissions

![rbac1](https://cloud.githubusercontent.com/assets/3372410/3280791/6bd8e618-f47e-11e3-9374-2d197e7ce7a3.png)

```php
$this->isGranted('post.create', $parameterProvider);
```

```php
public function AuthorizationService::isGranted($permissionGroup, ParameterProvider $parameterProvider)
{
    $roles = $this->roleService->getIdentityRoles();
    return $this->carbac->isGranted($roles, $permissionGroup, $parameterProvider);
}

public function CARBAC::isGranted($roles, $permissionGroup, ParameterProvider $parameterProvider)
{
    if ($roles instanceof RoleInterface) {
        $roles = [$roles];
    }

    $iterator = $this->traversalStrategy->getRolesIterator($roles);

    foreach ($iterator as $role) {
        /* @var RoleInterface $role */
        if ($role->hasPermission($permissionGroup)) {
            $permissions = $role->getPermissions($permissionGroup);
            foreach ($permissions as $permission) {
                if ($this->doMatch($permission, $parameterProvider) {
                    return true;
                }
            }
        }
    }

    return false;
}

protected function CARBAC::doMatch(PermissionInterface $permission, ParameterProvider $parameterProvider)
{
    $permissionParameters = $permission->getParameters();
    $providedParameters = $parameterProvider->getParameters();
    $diff = array_diff($permissionParameters, $providedParameters );
    return empty($diff);
}
```

**Problems with this implementation**

1. Superroles (like a global `Sysadmin`) are not possible with this approach, because the ParameterProvider must match exactly the PermissionParameters.
2. The `ParameterProvider` must return the same objects as `$permission->getParameters()` which is not ideal, because every ParameterProvider would have to have a n:m association with `PermissionParameter`s.

Here are some ideas how to solve the problems:

#### Use MatchStrategies

```php
public function CARBAC::isGranted($roles, $permissionGroup, ParameterProvider $parameterProvider)
{
    if ($roles instanceof RoleInterface) {
        $roles = [$roles];
    }

    $iterator = $this->traversalStrategy->getRolesIterator($roles);

    foreach ($iterator as $role) {
        /* @var RoleInterface $role */
        if ($role->hasPermission($permissionGroup)) {
            $permissions = $role->getPermissions($permissionGroup);
            foreach ($permissions as $permission) {
                if ($this->matchStrategy->doMatch($permission, $parameterProvider) {
                    return true;
                }
            }
        }
    }

    return false;
}

public function DiffMatchStrategy::doMatch(PermissionInterface $permission, ParameterProvider $parameterProvider)
{
    $permissionParameters = $permission->getParameters();
    $providedParameters = $parameterProvider->getParameters();
    $diff = array_diff($permissionParameters, $providedParameters );
    return empty($diff);
}

public function KeyValueMatchStrategy::doMatch(PermissionInterface $permission, ParameterProvider $parameterProvider)
{
    $providedParameters = $parameterProvider->getParameters();

    foreach ($providedParameters as $providedParameter) {
        $key = $providedParameter->getKey();
        $value = $providedParameter->getValue();
        if (!$permission->hasParameter($key, $value)) {
            return false;
        }
    }
    
    return true;
}
```

#### Defining super-permissions

A possibility to implement super-permissions could be the following:

* "article.create": {('tenant', 1)} // Create articles on tenant 1
* "article.create": {('tenant', 2)} // Create articles on tenant 2
* "article.create": {('tenant', null)} // Create articles on **all tenants**

* "article.update": {('tenant', 1), ('time', 31341415)} // Update articles on tenant 1 which have the timestamp `31341415`
* "article.update": {('tenant', 2), ('time', 12341325)} // Update articles on tenant 2 which have the timestamp `12341325`
* "article.update": {('tenant', null), ('time', 12341325)}  // Update articles **al tenants** which have the timestamp `12341325`
* "article.update": {('tenant', null), ('time', null)}  // Update articles **al tenants** regardless of the timestamp

Using `null` to identify super-permissions (universal permissions) could therefore be a possible strategy:

```php
public function KeyValueWithUniversalMatchStrategy::doMatch(PermissionInterface $permission, ParameterProvider $parameterProvider)
{
    $providedParameters = $parameterProvider->getParameters();

    foreach ($providedParameters as $providedParameter) {
        $key = $providedParameter->getKey();
        $value = $providedParameter->getValue();
        if (!$permission->hasParameter($key, $value) && !$permission->hasParameter($key, null)) {
            return false;
        }
    }
    
    return true;
}
```

### More research

* Keywords you might want to use: multi tenant, rbac, parametrized rbac, context aware rbac
* More resources
 * http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6596058&url=http%3A%2F%2Fieeexplore.ieee.org%2Fiel7%2F6589044%2F6596025%2F06596058.pdf%3Farnumber%3D6596058
 * http://www.deepdyve.com/lp/institute-of-electrical-and-electronics-engineers/a-multi-tenant-rbac-model-for-collaborative-cloud-services-ftr4FtpePl
 * http://scholar.google.de/scholar?q=parameterized+role+based+access+control&hl=de&as_sdt=0&as_vis=1&oi=scholart&sa=X&ei=8IOdU_6oM9T07AaTu4GoDw&ved=0CCAQgQMwAA

**Comment by bakura10** [comment]
One more resource: ABAC model http://csrc.nist.gov/projects/abac/july2013_workshop/july2013_abac_workshop_abac-sp.pdf

There is already an implementation for ZF2: https://github.com/Eye4web/Eye4webZf2Abac/tree/master/src/Eye4web/Zf2Abac

**Comment by claytondaley** [comment]
Yes.  We seem to be talking about features of ABAC.  A ZfcAbac would be nice (most people want ABAC when they find RBAC), but we probably shouldn't be trying to hide ABAC under the covers of RBAC.  If RBAC is right for your system (guest, registered user, subscriber, admin), use it.  If you need ABAC instead, use it instead.

**Comment by arekkas** [comment]
Agreed
