### ISSUE TITLE
If a child route is missing

### ISSUE THREAD

**Issue by internalsystemerror** [ZF-Commons/zfc-rbac#282]
Ok so, you have a basic admin route structure admin => /admin,
with child routes admin/users => /admin/users etc etc...
You setup a basic route guard for 'admin*' to be for the admin role only.
You navigate to a non defined url (e.g. /admin/thisisatest), you get a 404.

Although the reasons are obvious (if its not a defined route, no route match can be found, so the guard will never be called), this still took me a suprise as I initially expected the same guard to fire and to get a 401/403.

Essentially this would allow anyone to discover what is a valid url, and what isn't, even if they're logged in.

I'd like to suggest either:
a) this is clearly documented, if you were to use query string routes, could this be an issue?
b) a UrlGuard is created that wouldn't use routes but url's.

Thoughts?

**Comment by bakura10** [comment]
I think this is not a problem, and 404 seems more logical to me than 403. This is not an issue as soon as everything is properly protected. I have exactly the same for my API. If /users route exists but does not have auth => 403, if hitting /foooo and does not exist => returning 404. You should not trade correctness for pseudo-security :).

a) What do you mean? Which issue could query string introduce?

b) Regarding the UrlGuard, I'd prefer not to introduce this complexity. People using ZF2 are assumed to use routes.

**Comment by danizord** [comment]
@internalsystemerror I see your use case, but as @bakura10 said, the current behavior makes more sense from HTTP perspective (404 when a given resource does not exist).

About the query string routes, you should use `isGranted()` for dynamic stuff. ZfcRbac Guards are made for simple and specific static authorization config.

You have a valid use-case, but not for guards. So, I'm closing
