### ISSUE TITLE
RbacCollector is currently broken

### ISSUE THREAD

**Issue by dillchuk** [ZF-Commons/zfc-rbac#294]
After a change in ZendDeveloperTools, the RbacCollector is broken.  See here:
https://github.com/zendframework/ZendDeveloperTools/commit/d3432681aa32177a741ad23604a40af9ad454acb#commitcomment-11090423

**Comment by belgattitude** [comment]
Same issue for me, tried a PR here https://github.com/ZF-Commons/zfc-rbac/pull/296.

**Comment by danizord** [comment]
Fixed in #296
