### ISSUE TITLE
InMemoryRoleProvider can reuse role objects

### ISSUE THREAD

**Issue by Wilt** [ZF-Commons/zfc-rbac#322]
In the current setup the child role in a `HierarchicalRole` is another Role instance with the same name. This is because of how the `InMemoryRoleProvider` is creating the roles. For example [the `$memberRole` in the `InMemoryRoleProviderTest`](https://github.com/ZF-Commons/zfc-rbac/blob/master/tests/ZfcRbacTest/Role/InMemoryRoleProviderTest.php#L53) is not the same object as the first child role of the `$adminRole`.

It would be cool to change the setup so that these tests are successful. I also think it will save some memory because in this case the roles are instantiated only once.

    assertTrue($adminRole->getChildren()['member'] === $memberRole);
    assertTrue($memberRole->getChildren()['guest'] === $guestRole);

**Comment by danizord** [comment]
Looks good for me, can you provide a PR @Wilt?

**Comment by Wilt** [comment]
Here a [PR](https://github.com/ZF-Commons/zfc-rbac/pull/323)

**Comment by danizord** [comment]
Fixed by #325
