### ISSUE TITLE
Insecure IP guard example

### ISSUE THREAD

**Issue by kelunik** [ZF-Commons/zfc-rbac#331]
https://github.com/ZF-Commons/zfc-rbac/blob/master/docs/04.%20Guards.md#creating-custom-guards shows a simple `IpGuard` example.

```php
if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $clientIp = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $clientIp = $_SERVER['REMOTE_ADDR'];
}
```

This example is insecure as it simply tasks a HTTP header as client IP if it's there. Anybody can just send this header and fake the client IP that way. It should be removed and reduced to `$clientIp = $_SERVER['REMOTE_ADDR'];`.

**Comment by danizord** [comment]
@kelunik can you send a PR?

**Comment by kelunik** [comment]
Sure, see #332.
