### ISSUE TITLE
How to mock authorization service in ZF2 AbstractHTTPControllerTestCase

### ISSUE THREAD

**Issue by clemf** [ZF-Commons/zfc-rbac#334]
I've been having trouble mocking the authorization service in PHPUnit, and came across pull request #298. It looks like by the time the [AbstractHTTPControllerTestCase](https://github.com/zendframework/zend-test/blob/master/src/PHPUnit/Controller/AbstractHttpControllerTestCase.php) is loaded, the authorization service is already registered and cannot be mocked. I see that the pull request is supposed to make a work-around for this issue by adding setters to the role service, but I don't understand how that helps. How do use these setters to help mock authorization for my tests?

**Comment by danizord** [comment]
You can mock the `IdentityProviderInterface` and make it return an identity with the permissions you need:

```php
$authorizationService = $this->getApplicationServiceLocator()->get(AuthorizationService::class);
$identityProvider     = $this->prophesize(IdentityProviderInterface::class);
$identity             = $this->prophesize(IdentityInterface::class);

// Here you use the setter to inject your mocked identity provider
$authorizationService->setIdentityProvider($identityProvider->reveal());

$identityProvider->getIdentity()->shouldBeCalled()->willReturn($identity->reveal());
$identity->getRoles()->shouldBeCalled()->willReturn([/* roles here */]);
```

**Comment by andrconstruction** [comment]
Daniel have you a real work example with this code? Please link me.

**Comment by clemf** [comment]
@andrconstruction I had to set this aside a while back, but plan on implementing this next week and will update this issue then.

**Comment by andrconstruction** [comment]
I would be very grateful

**Comment by evanb2** [comment]
@danizord It looks like the setters are located in the RoleService not the AuthorizationService as you used in your example...

**Comment by clemf** [comment]
@danizord I appreciate your help with this, but I can't seem to solve my problem with the code you provided. It doesn't seem to matter what I mock because none of that happens until after zfc-rbac has already refused access. Apparently zfc-rbac has a higher priority than the mocking process in AbstractHttpControllerTestCase?

Is there any way around this? I was thinking of maybe creating a special test config file or hooking into an event...

**Comment by danizord** [comment]
@evanb2 and @clemf sorry, here is the updated version that mocks `RoleService` instead:

**Comment by danizord** [comment]
@evanb2 and @clemf sorry, here is the updated version that mocks `RoleService` instead:

```php
$roleService      = $this->getApplicationServiceLocator()->get(RoleService::class);
$identityProvider = $this->prophesize(IdentityProviderInterface::class);
$identity         = $this->prophesize(IdentityInterface::class);

// Here you use the setter to inject your mocked identity provider
$authorizationService->setIdentityProvider($identityProvider->reveal());

$identityProvider->getIdentity()->shouldBeCalled()->willReturn($identity->reveal());
$identity->getRoles()->shouldBeCalled()->willReturn([/* roles here */]);
```

**Comment by danizord** [comment]
@clemf 
>I appreciate your help with this, but I can't seem to solve my problem with the code you provided. It doesn't seem to matter what I mock because none of that happens until after zfc-rbac has already refused access. Apparently zfc-rbac has a higher priority than the mocking process in AbstractHttpControllerTestCase?

It should work if you inject the mocked identity provider before calling `$this->dispatch()` in `AbstractHttpControllerTestCase`.

**Comment by evanb2** [comment]
@danizord Thanks, it works!
