### ISSUE TITLE
Any Plans to make it compatible with ZF3?

### ISSUE THREAD

**Issue by manuakasam** [ZF-Commons/zfc-rbac#337]
hey guys, I've just fiddled around a bit seeing if i can make it compatible with zf3, but quite frankly I'm not.
I'm don't even understand some unit test messages so yeah, wondering if there's any plans by the maintainers to up the compatibility? =)

**Comment by danizord** [comment]
Hey @manuakasam! @prolic is working on ZF3 compatibility here #335.
