### ISSUE TITLE
What happened to the Guard namespace?

### ISSUE THREAD

**Issue by nasko** [ZF-Commons/zfc-rbac#339]
Hello guys,

I've been using `zfc-rbac` with a Zend Framework 2.* application for almost two years now.

Recently I decided to research and prepare a migration plan to move my application to ZF 3.
With a few exceptions, most of the vendor packages that I use are already ZF3-compatible to varying extents.
At first glance it looked like the `develop` branch of `zfc-rbac` was already headed in that direction, so I  updated my vendor package to use it. However, as soon as I accomplished that, my IDE immediately got  in pain and started reporting missing classes. I noticed that the whole `Guard` namespace was missing.

I haven't been involved in the development of `zfc-rbac`, neither directly, nor by contributing feedback, so please bear with me, in case this has already been discussed here. I only took a cursory glimpse at the issues list and failed to notice any entries, directly mentioning removal of namespaces.

Could someone give me any hints as to the ZendFramework 3 migration roadmap?

Thanks in advance!

**Comment by svycka** [comment]
@nasko zf3 support is WIP https://github.com/ZF-Commons/zfc-rbac/pull/335

**Comment by nasko** [comment]
Thanks @svycka! I've subscribed to the PR discussion.

The DoctrineORMModule is not ZF3-compatible either, so it seems I'll have enough time to refactor my application :-)

**Comment by webimpress** [comment]
@nasko DoctrineORMModule ZF3 support is also WIP https://github.com/doctrine/DoctrineORMModule/pull/479 ;)

**Comment by nasko** [comment]
@webimpress Yeah, subscribed to that PR too :-)

**Comment by danizord** [comment]
@nasko also, the develop branch is a migration to middleware concept, so some stuff like guards was removed and will be completely rewrite.

**Comment by svycka** [comment]
maybe wrong place to ask, but @danizord if guards are removed how we will protect controllers that comes for example from zfcuser? and does it mean that zend-mvc will not be supported anymore?
