### ISSUE TITLE
Does not support EventManager 3.0 and throws fatal error

### ISSUE THREAD

**Issue by svycka** [ZF-Commons/zfc-rbac#347]
first doesn't have `zendframework/zend-eventmanager` as dependancy in composer.json but it is used in the library this worked because `zendframework/zend-mvc` has it and now when `zendframework/zend-mvc` allows `zendframework/zend-eventmanager:3.0` we have `zendframework/zend-eventmanager:3.0` installed and this error:

```
Fatal error: Declaration of ZfcRbac\Guard\AbstractGuard::attach(Zend\EventManager\EventManagerInterface $events) must be compatible with Zend\EventManager\ListenerAggregateInterface::attach(Zend\EventManager\EventManagerInterface $events, $priority = 1) in /var/www/fam/vendor/zf-commons/zfc-rbac/src/ZfcRbac/Guard/AbstractGuard.php on line
```

in master this is fixed by adding `zendframework/zend-eventmanager:3.0` support so can we have a release a bit faster?

**Comment by svycka** [comment]
as workaround I had to add `"zendframework/zend-eventmanager": "^2.6.3"` to my project composer.json even if I not use event-manager.

**Comment by bakura10** [comment]
Current master has a looser dependency: https://github.com/ZF-Commons/zfc-rbac/blob/master/composer.json#L32

Can you please try to try using the "dev-master" dependency of zfc-rbac? We're thinking of soon creating a new version of ZfcRbac with those updated dependencies.

**Comment by svycka** [comment]
@bakura10 sorry I have no plans using dev version but that fatal error yes dev-master fixed it as far as I can see.

**Comment by bakura10** [comment]
I was not asking using a dev version, just to make sure that the master version indeed solves the issue, as we should tag it soon :)

**Comment by svycka** [comment]
@bakura10 dev-master working on my dev server and tests pass so I guess should work.

Is there any clues when it will be released because soon so far means at least few months and I don't see the end :D

**Comment by bakura10** [comment]
Haha it all depends on @danizord when he can reviews the code :p.

**Comment by webimpress** [comment]
@bakura10 @svycka @danizord I can confirm - dev-master works fine also in my project. Thanks!

**Comment by svycka** [comment]
well reviews often is done before merging to master so.. :D anyway just saying that latest version 2.5.6 throws fatal error

**Comment by bakura10** [comment]
Yeah you're correct :D. As said in #348 the only issue for now is that I've just pulled the project, tried to run the tests but experienced lot of errors :/. So I'll need to check that before to make sure I'm not missing anything.

**Comment by bakura10** [comment]
I've tagged 2.6.0. This should fix this issue.
