### ISSUE TITLE
Looking for a new maintainer(s)

### ISSUE THREAD

**Issue by bakura10** [ZF-Commons/zfc-rbac#350]
Hi everyone,

As some of you may know, I'm no longer that much into PHP world (my job is now more about front-end). While I still continue to do back-end work with @danizord who work for us, our projects are for a very specific platform that do not require the usage of this module.

Because of its popularity, the big incoming projects (port to middleware), I feel I can't any longer properly maintain this package, and I'd like to have 1-2 people taking the lead on this one.

@basz and @prolic , you're obviously the candidates that came in my mind due to your recent work on it, so if you're interested please let me know and I'll give you access from now one.

Thanks for your cooperation and once again sorry for the time it has taken to me to release the ZF3 compatibility version.

**Comment by prolic** [comment]
@danizord @bakura10 
Thank you very much. I just spoke with @basz and we both feel very honored. We will discuss this and will get back to use this weekend (hopefully).

**Comment by bakura10** [comment]
Thanks a lot for considering taking the lead of this project. That would be highly appreciated for me :). Let me know!

**Comment by webimpress** [comment]
I'm happy to help if you need any help ;-)

**Comment by chukShirley** [comment]
I'm happy to help as well. I certainly wouldn't be able to lead, but please let me know how I can assist.

**Comment by bakura10** [comment]
Thanks a lot everyone, I will wait for basz and prolic answers as they have definitely work a lot on the module so they know it pretty well, but any help in the future for reviewing any PR is always welcome and you can always help at your level :).
