### ISSUE TITLE
Missing use statement in ZfcRbac\Initializer\AuthorizationServiceInitializer

### ISSUE THREAD

**Issue by DennisDobslaf** [ZF-Commons/zfc-rbac#351]
AuthorizationServiceInitializer @ Line 51 asks for $serviceLocator instanceof AbstractPluginManager
https://github.com/ZF-Commons/zfc-rbac/blob/master/src/ZfcRbac/Initializer/AuthorizationServiceInitializer.php#L51

but
use Zend\ServiceManager\AbstractPluginManager; 
is missing

**Comment by bakura10** [comment]
2.6.1 has been tagged. Thanks!
