### ISSUE TITLE
What is the plan of 3.0 release?

### ISSUE THREAD

**Issue by svycka** [ZF-Commons/zfc-rbac#385]
Soon I will need this module for a new project and would like to know what is holding 3.0 release or when it will be released. I will use it with zend-expressive and would be a lot easier to do it than with 2.0

**Comment by basz** [comment]
Besides documentation I believe is it pretty much ready. I won't mind a 3 (pre)release either

What shall we do?

**Comment by prolic** [comment]
We can release alpha 1 and bring missing stuff then.

**Comment by basz** [comment]
Ok, sounds like a plan. I don’t expect the api to change anymore, but an alpha might attract some more users to test the thing

> Op 5 apr. 2018 om 09:16 heeft Sascha-Oliver Prolic <notifications@github.com> het volgende geschreven:
> 
> We can release alpha 1 and bring missing stuff then.
>

**Comment by svycka** [comment]
sounds good to me

**Comment by svycka** [comment]
so if everyone agrees maybe someone can tag release?

**Comment by basz** [comment]
"just did it"

**Comment by svycka** [comment]
thanks
