### ISSUE TITLE
HierarchicalRoleInterface problem

### ISSUE THREAD

**Issue by svycka** [ZF-Commons/zfc-rbac#387]
here https://github.com/ZF-Commons/zfc-rbac/blob/develop/src/Role/HierarchicalRoleInterface.php#L36 maybe we could change the return type to `iterable`?
````php
public function getChildren(): array;
// to
public function getChildren(): iterable;
````
Then when working with doctrine I could just return ArrayCollection, but now I have to do this:
````php
public function getChildren(): array
{
    return $this->children->toArray();
}
`````

**Comment by basz** [comment]
Sounds reasonable
