### ISSUE TITLE
Migrate to Laminas

### ISSUE THREAD

**Issue by demiankatz** [ZF-Commons/zfc-rbac#391]
With the deprecation of all things Zend Framework, are there any plans to move this library to a Laminas space? If not, is there a recommended Laminas alternative to this module?

If there is a need for Laminas migration but nobody has the time to do it, I'm certainly willing to help with the effort -- but I want to be sure this is still an active concern first, so I can decide whether to invest time in helping with this project, or else in changing my own project's dependencies to work around it.

Thanks for your time!

**Comment by prolic** [comment]
good question. @basz any plans?

**Comment by basz** [comment]
Yes I would want to migrate to Laminas. Currently doing some other libs so not happening this week.

**Comment by prolic** [comment]
@basz can you communicate with the rest of ZF-Commons team? Maybe they have a plan for migrating the github organization as well.

**Comment by basz** [comment]
Hello Sirs, I'm targeting all ZFCommon Members here (I know some of you are not active anymore):

@bakura10 @Bittarman @cosmin-harangus @danizord @Danielss89 @DASPRiD @EvanDotPro @GeeH @juriansluiman @Thinkscape @weierophinney

Is there a plan to upgrade these libraries to Laminas? I'm not sure about the current usages of any of the repos in this organisation. Maybe some of them simple should be deprecated or archived. Personally I only still use zfc-rbac (3.0-alpha) in one project and am able to keep keep minor contributions going.

**Comment by demiankatz** [comment]
Thanks for moving this along, @basz. Let me know if I can be of any assistance; I've been working on migrating my own application, so if it would save you any time for me to open an initial pull request with the Zend --> Laminas renaming, etc., I'm certainly willing to start. I can also test this with my application post-migration if you need that as well.

**Comment by basz** [comment]
closed via #392 and #393, a review and/or test would be appreciated

**Comment by demiankatz** [comment]
@basz, many thanks for this. I've left a review on #392 and tested it. I don't use the newer version, so I didn't review the second PR, but I suspect that some of my general #392 comments will also apply to #393.
